### ISSUE TITLE
 #include "raylib.h"

### ISSUE THREAD

**Issue by dd123-a** [Bowserinator/TPTBox#3]
"==== Building raylib (debug_x64) ===="
"==== Building TPTBox (debug_x64) ===="
"Air.cpp"
"Brush.cpp"
In file included from ../game/src/interface/brush/Brush.cpp:1:
../game/src/interface/brush/Brush.h:4:10: fatal error: raylib.h: No such file or directory
 #include "raylib.h"
          ^~~~~~~~~~
compilation terminated.
mingw32-make[1]: *** [TPTBox.make:302: obj/x64/Debug/TPTBox/Brush.o] Error 1
mingw32-make: *** [Makefile:54: TPTBox] Error 2

**Comment by git4rker** [comment]
alright xd
